## Assignment 3
STUDENT INFO: 
1) Name: 
- NUR FIRZANA BINTI BADRUS HISHAM (A23CS0156)
- NURUL ADRIANA BINTI KAMAL JEFRI (A23CS0258)
- Harini A/P Sangaran (A23CS0081)

2) Section: 02

# Rainfall Data Analysis Assignment (100 Marks, Due 6th July 2025)

You are provided with a rainfall dataset recording monthly measurements from various weather stations across different regions. The dataset includes rainfall (mm), number of rainy days, maximum and minimum temperatures, and whether the station is in an urban or rural area.

Dataset columns:

- `Region`: Name of the region (e.g., North, South, East, West)
- `Year`: Year of measurement
- `Month`: Month (e.g., Jan, Feb, ..., Dec)
- `Station`: Weather station name/ID (e.g., StationA, StationB)
- `Rainfall_mm`: Rainfall amount in millimeters
- `RainyDays`: Number of days in the month with rain
- `MaxTemp_C`: Maximum temperature recorded in that month (°C)
- `MinTemp_C`: Minimum temperature recorded in that month (°C)
- `UrbanRural`: "Urban" or "Rural"

## Part 1: Data Exploration ( 15 Marks)

1. Load the data into a pandas DataFrame. (2 Marks)
2. Display the first 5 rows of the DataFrame. (2 Marks)
3. Check for and handle any missing values. (6 Marks)
4. Provide summary statistics for all numeric columns. (5 Marks)

In [63]:
#Write your code here
# 1. Load the data into a pandas DataFrame. 
import pandas as pd  

print("\nLoad the dataset: ")
rainfall = pd.read_csv("Rainfall.csv", header=None)  
rainfall

Load the dataset:

                                                    0
0   Region,Year,Month,Station,Rainfall_mm,RainyDay...
1       North,2023,Jan,StationA,56.2,9,12.1,2.5,Urban
2      North,2023,Feb,StationA,72.1,12,14.7,3.0,Urban
3      North,2023,Jan,StationB,60.5,10,11.2,1.8,Rural
4      South,2023,Jan,StationC,81.0,13,19.6,7.2,Urban
5      South,2023,Feb,StationC,63.4,11,20.1,7.7,Urban
6        East,2023,Jan,StationD,45.7,8,15.4,5.6,Rural
7       East,2023,Feb,StationD,59.6,10,17.9,6.2,Rural
8       West,2023,Jan,StationE,77.4,12,16.8,4.9,Urban
9       West,2023,Feb,StationE,84.2,13,18.2,5.3,Urban
10     North,2023,Mar,StationB,61.5,11,15.0,3.2,Rural

In [19]:
# 2. Display the first 5 rows of the DataFrame.
print("\nFirst 5 rows: ")
rainfall.head()

First 5 rows:

                                                   0
0  Region,Year,Month,Station,Rainfall_mm,RainyDay...
1      North,2023,Jan,StationA,56.2,9,12.1,2.5,Urban
2     North,2023,Feb,StationA,72.1,12,14.7,3.0,Urban
3     North,2023,Jan,StationB,60.5,10,11.2,1.8,Rural
4     South,2023,Jan,StationC,81.0,13,19.6,7.2,Urban

In [61]:
# 3. Check for and handle any missing values

print("\nAfter handle the values of data: ")
column_names = ['Region','Year','Month','Station','Rainfall_mm','RainyDays','MaxTemp_C','MinTemp_C','UrbanRural']

rainfall_df = rainfall[0].str.split(',', expand=True) 

rainfall_df.columns = column_names  
rainfall_df = rainfall_df.drop(index=0).reset_index(drop=True) 

rainfall_df

After handle the values of data:

,Region,Year,Month,Station,Rainfall_mm,RainyDays,MaxTemp_C,MinTemp_C,UrbanRural
0,North,2023,Jan,StationA,56.2,9,12.1,2.5,Urban
1,North,2023,Feb,StationA,72.1,12,14.7,3.0,Urban
2,North,2023,Jan,StationB,60.5,10,11.2,1.8,Rural
3,South,2023,Jan,StationC,81.0,13,19.6,7.2,Urban
4,South,2023,Feb,StationC,63.4,11,20.1,7.7,Urban
5,East,2023,Jan,StationD,45.7,8,15.4,5.6,Rural
6,East,2023,Feb,StationD,59.6,10,17.9,6.2,Rural
7,West,2023,Jan,StationE,77.4,12,16.8,4.9,Urban
8,West,2023,Feb,StationE,84.2,13,18.2,5.3,Urban
9,North,2023,Mar,StationB,61.5,11,15.0,3.2,Rural

In [23]:
# 4. Provide summary statistics for all numeric columns. 

print("\n------Summary Statistics: -------")
rainfall_df.describe()

------Summary Statistics: -------

,Region,Year,Month,Station,Rainfall_mm,RainyDays,MaxTemp_C,MinTemp_C,UrbanRural
count,10,10,10,10,10,10,10,10,10
unique,4,1,3,5,10,6,10,10,2
top,North,2023,Jan,StationA,56.2,12,12.1,2.5,Urban
freq,4,10,5,2,1,2,1,1,6

## Part 2: Grouping and Aggregation (30 Marks)

1. For each **Station**, compute: (6 Marks)
    - Total rainfall 
    - Average number of rainy days 
    - Average maximum temperature 
    - Average minimum temperature

In [69]:
#Write your code here
# Convert numeric columns
for col in ['Year', 'Rainfall_mm', 'RainyDays', 'MaxTemp_C', 'MinTemp_C']:
    rainfall_df[col] = pd.to_numeric(rainfall_df[col])

print("\nTotal rainfall(mm) for each Station: ")
total = rainfall_df.groupby('Station')['Rainfall_mm'].sum() 
print(total)

print("\nAverage Number of Rainy Days for each Station: ")
avg_rainy = rainfall_df.groupby('Station')['RainyDays'].mean()
print(avg_rainy)

print("\nAverage Maximum Temperature for each Station: ")
avg_maxT = rainfall_df.groupby('Station')['MaxTemp_C'].mean()
print(avg_maxT)

print("\nAverage Minimum Temperature for each Station: ")
avg_minT = rainfall_df.groupby('Station')['MinTemp_C'].mean()
print(avg_minT)

Total rainfall(mm) for each Station:
Station
StationA    128.3
StationB    122.0
StationC    144.4
StationD    105.3
StationE    161.6
Name: Rainfall_mm, dtype: float64

Average Number of Rainy Days for each Station:
Station
StationA    10.5
StationB    10.5
StationC    12.0
StationD     9.0
StationE    12.5
Name: RainyDays, dtype: float64

Average Maximum Temperature for each Station:
Station
StationA    13.40
StationB    13.10
StationC    19.85
StationD    16.65
StationE    17.50
Name: MaxTemp_C, dtype: float64

Average Minimum Temperature for each Station:
Station
StationA    2.75
StationB    2.50
StationC    7.45
StationD    5.90
StationE    5.10
Name: MinTemp_C, dtype: float64

2. For each **Region & UrbanRural** combination, calculate: (6 Marks)
    - Average rainfall
    - Average maximum temperature
    - Average number of rainy days

In [71]:
#Write your code here
print("\nAverage rainfall based on Urban&Rural: ")
avg_rainfall = rainfall_df.groupby(['Region','UrbanRural'])['Rainfall_mm'].mean()
print(avg_rainfall)

print("\nAverage Maximum Temperature based on Region&UrbanRural: ")
avg_temp = rainfall_df.groupby(['Region','UrbanRural'])['MaxTemp_C'].mean()
print(avg_temp)

print("\nAverage number of Rainy Days based on Region&UrbanRural: ")
avg_rainyRegion = rainfall_df.groupby(['Region','UrbanRural'])['RainyDays'].mean()
print(avg_rainyRegion)

Average rainfall based on Urban&Rural:
Region  UrbanRural
East    Rural         52.65
North   Rural         61.00
        Urban         64.15
South   Urban         72.20
West    Urban         80.80
Name: Rainfall_mm, dtype: float64

Average Maximum Temperature based on Region&UrbanRural:
Region  UrbanRural
East    Rural         16.65
North   Rural         13.10
        Urban         13.40
South   Urban         19.85
West    Urban         17.50
Name: MaxTemp_C, dtype: float64

Average number of Rainy Days based on Region&UrbanRural:
Region  UrbanRural
East    Rural          9.0
North   Rural         10.5
        Urban         10.5
South   Urban         12.0
West    Urban         12.5
Name: RainyDays, dtype: float64

3. For each **Month** and **Region**, calculate: (6 Marks)
    - Total rainfall
    - Mean rainfall
    - Minimum and maximum rainfall

In [73]:
#Write your code here
totalRainfall_month = rainfall_df.groupby(['Month','Region'])[['Rainfall_mm']].sum()

meanRainfall_month = rainfall_df.groupby(['Month','Region'])[['Rainfall_mm']].mean()

minMaxRainfall_month = rainfall_df.groupby(['Month','Region'])[['MinTemp_C','MaxTemp_C']].mean()

print("\nTotal Rainfall based on Month&Region: ")
print(totalRainfall_month)

print("\nMean Rainfall based on Month&Region: ")
print(meanRainfall_month)

print("\nMinimum and Maximum Rainfall based on Month&Region: ")
print(minMaxRainfall_month)

Total Rainfall based on Month&Region:
              Rainfall_mm
Month Region
Feb   East           59.6
      North          72.1
      South          63.4
      West           84.2
Jan   East           45.7
      North         116.7
      South          81.0
      West           77.4
Mar   North          61.5

Mean Rainfall based on Month&Region:
              Rainfall_mm
Month Region
Feb   East          59.60
      North         72.10
      South         63.40
      West          84.20
Jan   East          45.70
      North         58.35
      South         81.00
      West          77.40
Mar   North         61.50

Minimum and Maximum Rainfall based on Month&Region:
              MinTemp_C  MaxTemp_C
Month Region
Feb   East         6.20      17.90
      North        3.00      14.70
      South        7.70      20.10
      West         5.30      18.20
Jan   East         5.60      15.40
      North        2.15      11.65
      South        7.20      19.60
      West         4.90      16.80
Mar   North        3.20      15.00

4. Find the **Region and Month** with the highest recorded rainfall in the dataset. (4 Marks)

In [5]:
#Write your code here

5. For each **Year** and **UrbanRural** group, calculate: (4 Marks)
    - Average rainfall
    - Minimum rainfall
    - Maximum rainfall

In [6]:
#Write your code here

6. For each **Region**, calculate the average temperature range per month (i.e., average of MaxTemp_C - MinTemp_C). (4 Marks)

In [8]:
#Write your code here

## Part 3: Data Visualization (matplotlib) (40 Marks)

1. **Bar Chart:**  (8 Marks)
   - Plot total rainfall by region, colored by Urban/Rural.
   - Add value labels, gridlines, axis labels, title, and adjust bar width for clarity.

In [9]:
#Write your code here

2. **Grouped Bar Chart:**  (6 Marks)
   - Show average monthly rainfall for each station.
   - Use different colors for each station, include a legend, rotate x-tick labels, and increase figure size for readability.

In [10]:
#Write your code here

3. **Line Plot:**  (6 Marks)
   - Show the trend of rainfall over months for at least two selected stations.
   - Use markers, dashed lines, highlight the month with maximum rainfall, and format the x-axis for months.

In [ ]:
#Write your code here

4. **Boxplot:**  (6 Marks)
   - Display rainfall distributions by region and by Urban/Rural.
   - Use custom box colors, highlight outliers, and set y-axis limits.

In [14]:
#Write your code here

5. **Scatter Plot:**  (6 Marks)
   - Visualize the relationship between rainfall and maximum temperature, colored by region.
   - Add axis labels, legend, gridlines, and an appropriate title.

In [15]:
#Write your code here

6. **Heatmap:**  
   - Create a heatmap showing mean monthly rainfall for each region (Month on x-axis, Region on y-axis).
   - Add color bar, axis labels, and title.

In [16]:
#Write your code here

7. **Formatting (for all plots):** (8 Marks)
   - Use descriptive titles, axis labels, and legends.
   - Increase font size for readability.
   - Save each figure as an image file (`.png`).
   - Use `plt.tight_layout()` for proper spacing.

In [18]:
#Write your code here

## Part 4: Bonus Tasks (15 Marks)

1. Annotate at least one plot with the value and label of the highest/lowest point. (5 Marks)

In [22]:
#Write your code here

2. Create a **facet/grid plot** comparing rainfall trends by region and Urban/Rural status. (5 Marks)

In [20]:
#Write your code here

3. Write a brief summary (in a Markdown cell) of your main insights from the data and visualizations. (5 Marks)

#Write your summary here